[package]
name = "exec-logger"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"

[[bin]]
name = "exec_logger"
path = "src/main.rs"

[lib]
name = "exec_logger"
path = "src/lib.rs"

[dependencies]
bcc = "0.0.17"
byteorder = "1.3"
ctrlc = "3.1"
failure = "0.1"
libc = "0.2"
